<?php 
include("../bd/conexion.php");

$link=Conectarse();


$Reserva=$_REQUEST['numeroreserva'];
$Usuario=$_REQUEST['usuario'];
$TIPO=$_REQUEST['tipo'];

/* INICIO INSERTAR RESERVA*/
$Sql="INSERT INTO [020BDCOMUN].DBO.PRE_REQUISD(CODIGOPRE_REQUISD,CANTPRE_REQUISD,TIPOPRE_REQUISD,USUARIO)
SELECT DRV.CODIGO,DRV.CANTIDAD-(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))),'$TIPO','$Usuario'
 FROM [020BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[020BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO LEFT JOIN [011BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND S.STALMA='01' INNER JOIN [011BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$Usuario' 
 AND DRV.TIPO='$TIPO' AND M.AFSTOCK='S' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,M.AUNIDAD,S.STSKDIS
HAVING ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))<DRV.CANTIDAD 
";

$Sql1="INSERT INTO [020BDCOMUN].DBO.RESERVA_DET (NRORESERVA,CODIGO,CANTIDAD,CANT_PEND)
(/*CANT_DISP>=CANT_SOL*/
SELECT '$Reserva',DRV.CODIGO,DRV.CANTIDAD,DRV.CANTIDAD
 FROM [020BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[020BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO LEFT JOIN [011BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND S.STALMA='01' INNER JOIN [011BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$Usuario' AND M.AFSTOCK='S' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,M.AUNIDAD,S.STSKDIS
HAVING ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))>=DRV.CANTIDAD  AND  
ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))<>0  AND ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))>=1 )
UNION
(/*CANT_DISP<CANT_SOL AND CANT_DISP <> 0*/
SELECT '$Reserva',DRV.CODIGO,ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0)) AS CANT_DISP,
ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0)) AS CANT_DISP
 FROM [020BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[020BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO LEFT JOIN [011BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND S.STALMA='01' INNER JOIN [011BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$Usuario' AND M.AFSTOCK='S' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,M.AUNIDAD,S.STSKDIS
HAVING ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))<=DRV.CANTIDAD  AND  
ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))<>0 AND ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))>=1 
)
";



$Sql2="DELETE FROM [020BDCOMUN].DBO.DATOS_RSV WHERE USUARIO='$Usuario' AND TIPO='$TIPO'";

$result=mssql_query($Sql);

if (!$result){echo "Error al guardar";}

else {
	$result1=mssql_query($Sql1);
    $result2=mssql_query($Sql2);
?>

<script>
window.location = "../pages/editar-reserva?reserva="+<?php echo $Reserva;?>;
</script>



<?php

}

?>